### ISSUE TITLE
Logs are never shipped to s3? version 0.5.6

### ISSUE THREAD

**Issue by ajohnstone** [fluent/fluent-plugin-s3#73] opened 2015-03-02 16:51 UTC
Logs are never shipped to s3? Write never seems to be called? Any pointers whats wrong?

```
fluent-gem list | grep s3
fluent-plugin-s3 (0.5.6)

```

fluent configuration
```
<source>
  type tail
  path /var/lib/docker/containers/*/*-json.log
  pos_file /var/log/fluentd-docker.pos
  #time_format %Y-%m-%dT%H:%M:%S 
  tag docker.*
  format json
  refresh_interval 1
  log_level debug
</source>

<match docker.var.lib.docker.containers.*.*.log>
  type record_reformer
  container_id ${tag_parts[5]}
  tag docker.all
  log_level debug
</match>

<match docker.all>
  type file
  path /var/log/docker/*.log
  format json
  include_time_key true
  log_level debug
</match>

<match docker.all>
  type s3
  s3_bucket photobox-services-logs
  s3_region eu-west-1
  path logs
  buffer_type memory
  #buffer_path /var/log/fluent/s3
  s3_object_key_format %{path}/events/ts=%{time_slice}/events_%{index}-%{hostname}.%{file_extension}
  time_slice_format %Y%m%d-%H
  auto_create_bucket true
  check_apikey_on_start true
  format out_file
  time_slice_format %Y%m%d-%H
  time_slice_wait 1m
  utc
  log_level debug
</match>
```

logs are being initialised
```
2015-03-02 16:43:57 +0000 [info]: fluent/engine.rb:124:block in configure: adding match pattern="docker.all" type="s3"
2015-03-02 16:43:57 +0000 [trace]: fluent/plugin.rb:72:register_impl: registered output plugin 's3'
2015-03-02 16:43:57 +0000 [info]: plugin/in_tail.rb:475:initialize: following tail of /var/lib/docker/containers/3907f6c79687f6ceafcebbeecf4c35d1e4866aebd9019671d9dc373a4bf74a7a/3907f6c79687f6ceafcebbeecf4c35d1e4866aebd9019671d9dc373a4bf74a7a-json.log
2015-03-02 16:43:57 +0000 [info]: plugin/in_tail.rb:475:initialize: following tail of /var/lib/docker/containers/8c4149cd7aa731155700026a5f6db0b9f26b170b766a67795f8a1a1c93d4ba21/8c4149cd7aa731155700026a5f6db0b9f26b170b766a67795f8a1a1c93d4ba21-json.log

```

Permissions correct on IAM role.
```
 aws s3 ls photobox-services-logs
                           PRE elb/

```
docker.all has logs written
```
 tail -n1 /var/log/docker/19700101.b51050ecb0d011c7c.log 
{"log":"[raft]16:44:28.648224 setCommitIndex.set.result index: 1120514, entries index: 273\n","stream":"stdout","container_id":"c76e5773b44592d08d883a74070934b5e4bab34b286e8f3faf7ee93bd74698b7","log_level":"debug","time":"1970-01-01T00:33:35+00:00"}

tail -n1 /var/lib/docker/containers/*/*-json.log | head -n10
==> /var/lib/docker/containers/379cc31c1efd3b4df5c8b2df7cfc1a6f13c0aa5e58031b00948b44ce89ce6175/379cc31c1efd3b4df5c8b2df7cfc1a6f13c0aa5e58031b00948b44ce89ce6175-json.log <==
{"log":"\n","stream":"stdout","time":"2015-03-02T16:47:40.809578959Z"}
...
```

**Comment by repeatedly** [comment] 2015-03-02 17:19
Do you wait one hour?

**Comment by ajohnstone** [comment] 2015-03-02 17:25
Is there an option to flush sooner? I've been probably restarting the process sooner than one hour?

**Comment by repeatedly** [comment] 2015-03-02 17:30
See following documents. Send signal or change buffer parameters.

http://docs.fluentd.org/articles/signals
http://docs.fluentd.org/articles/buffer-plugin-overview#time-sliced-plugin-overview

**Comment by repeatedly** [comment] 2015-03-03 07:00
Close this issue.

BTW, if you have a question, please use mailing list first: https://groups.google.com/forum/#!forum/fluentd
Mailing list is better than github issue. This issue is mainly for reporting a bug or feature suggestion.

**Closed by repeatedly** 2015-03-03 07:00 UTC

**Comment by ajohnstone** [comment] 2015-03-03 10:43
I was already running this and reloading with SIGHUP as it was the root process in a docker container.
I've used SIGUSR1 and also waited over night for the logs to be flushed. Nothing has been written, however it has to the file plugin. I've added additional debugging to the plugin and this is why I raised as a ticket here. I never see the write method called.

Any other pointers?

```
  <match docker.all>
    type s3
    s3_bucket photobox-services-logs
    s3_region eu-west-1
    path logs/
    buffer_type memory
    s3_object_key_format %{path}/events/ts=%{time_slice}/events_%{index}-%{hostname}.%{file_extension}
    time_slice_format %Y%m%d-%H
    auto_create_bucket true
    check_apikey_on_start false
    format out_file
    time_slice_wait 1m
    utc 
    log_level debug
    buffer_chunk_limit 256m
    buffer_queue_limit 128
    flush_interval 60s
    disable_retry_limit false
    retry_limit 17
    retry_wait 1s
  </match>
```

**Comment by ajohnstone** [comment] 2015-03-03 14:10
I've also tried this from the documentation... and still to no avail

```
<match docker.all>
  type s3

  s3_bucket photobox-services-logs
  s3_region eu-west-1
  path logs
  buffer_path /var/log/fluent/s3

  time_slice_format %Y%m%d%H
  time_slice_wait 1m
  utc

  buffer_chunk_limit 256m
  flush_interval 1m
</match>

```

**Comment by repeatedly** [comment] 2015-03-03 14:18
Ah, wait. I found the cause.
You should use out_copy plugin for this case.
See: http://docs.fluentd.org/articles/config-file#match-order

**Comment by ajohnstone** [comment] 2015-03-03 15:24
@repeatedly  That solved it. Thanks for your help Masahiro, much appreciated. :+1:
